"""[Add season to applications]

Revision ID: 1a99b2b77c58
Revises: 44c5a4650146
Create Date: 2015-11-03 23:41:09.377153

"""

# revision identifiers, used by Alembic.
revision = '1a99b2b77c58'
down_revision = '44c5a4650146'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voter_application', sa.Column('season', sa.Integer(), nullable=False, server_default="2015"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voter_application', 'season')
    ### end Alembic commands ###
