"""Add remind options and flair to user

Revision ID: 209673ce1f50
Revises: 31630f2147ed
Create Date: 2014-10-07 03:30:33.313802

"""

# revision identifiers, used by Alembic.
revision = '209673ce1f50'
down_revision = '31630f2147ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('emailReminders', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('flair', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('pmReminders', sa.Boolean(), nullable=True))
    ### end Alembic commands ###

    # a couple of teams have the wrong png_name
    op.execute("UPDATE team SET png_name='ucf' WHERE id=46")    
    op.execute("UPDATE team SET png_name='cin' WHERE id=52")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pmReminders')
    op.drop_column('user', 'flair')
    op.drop_column('user', 'emailReminders')
    ### end Alembic commands ###
