"""Named unique constraint.

Revision ID: 29cc98b4406b
Revises: 406bfd13e07c
Create Date: 2015-01-24 23:03:25.957617

"""

# revision identifiers, used by Alembic.
revision = '29cc98b4406b'
down_revision = '406bfd13e07c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('oneballot', 'ballot', ['user_id', 'poll_id'])
    op.drop_constraint(u'user_id', 'ballot')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'user_id', 'ballot', ['user_id', 'poll_id'])
    op.drop_constraint('oneballot', 'ballot')
    ### end Alembic commands ###
