"""Added emailConfirmed field to User model.

Revision ID: 3993e089e5a6
Revises: a0c44ab3695
Create Date: 2014-09-26 22:33:55.779734

"""

# revision identifiers, used by Alembic.
revision = '3993e089e5a6'
down_revision = 'a0c44ab3695'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('emailConfirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'emailConfirmed')
    ### end Alembic commands ###
