"""UniqueConstraint on ballot for (user_id, poll_id) pair.

Revision ID: 406bfd13e07c
Revises: 7ceaa5c9096
Create Date: 2015-01-24 14:28:27.069374

"""

# revision identifiers, used by Alembic.
revision = '406bfd13e07c'
down_revision = '7ceaa5c9096'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ballot', ['user_id', 'poll_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ballot')
    ### end Alembic commands ###
