"""Add one ballot per user per poll constraint

Revision ID: 44c5a4650146
Revises: 7ceaa5c9096
Create Date: 2015-01-24 23:19:36.922859

"""

# revision identifiers, used by Alembic.
revision = '44c5a4650146'
down_revision = '7ceaa5c9096'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('oneballot', 'ballot', ['user_id', 'poll_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('oneballot', 'ballot')
    ### end Alembic commands ###
