"""add applicationFlag to User

Revision ID: 47266dd94e01
Revises: 1a5977b16f8
Create Date: 2014-10-23 07:47:37.750517

"""

# revision identifiers, used by Alembic.
revision = '47266dd94e01'
down_revision = '1a5977b16f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('applicationFlag', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'applicationFlag')
    ### end Alembic commands ###
