"""initial migration

Revision ID: a0c44ab3695
Revises: None
Create Date: 2014-09-20 12:52:38.566580

"""

# revision identifiers, used by Alembic.
revision = 'a0c44ab3695'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('openTime', sa.DateTime(), nullable=True),
    sa.Column('closeTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('u', 'p', 'a'), nullable=True),
    sa.Column('accessToken', sa.String(length=30), nullable=True),
    sa.Column('refreshToken', sa.String(length=30), nullable=True),
    sa.Column('refreshAfter', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=75), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('flair', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('conference', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('onevotes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ballot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ballot_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.Column('reason', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

    user_table = table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nickname', sa.String(length=20), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('role', sa.Enum('u', 'p', 'a'), nullable=True),
                    sa.Column('accessToken', sa.String(length=30), nullable=True),
                    sa.Column('refreshToken', sa.String(length=30), nullable=True),
                    sa.Column('refreshAfter', sa.DateTime(), nullable=True))

    op.bulk_insert(user_table,
        [
            { 'id' : 1, 'nickname' : 'Concision', 'email' : '', 'role' : 'a' }
        ])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('ballot')
    op.drop_table('result')
    op.drop_table('team')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('poll')
    ### end Alembic commands ###
