"""Adds voter_event table

Revision ID: de507a7c103
Revises: 209673ce1f50
Create Date: 2014-10-08 19:58:45.085825

"""

# revision identifiers, used by Alembic.
revision = 'de507a7c103'
down_revision = '209673ce1f50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voter_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_voter', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voter_event')
    ### end Alembic commands ###
